export const APP_NAME = "Readymetry";
export const APP_TAGLINE = "Certification Readiness Engine";
export const APP_URL = process.env.NEXT_PUBLIC_APP_URL ?? "https://readymetry.com";

export const ROUTES = {
  home: "/",
  pricing: "/pricing",
  certifications: "/#certifications",
  about: "/about",
  contact: "/contact",
  privacy: "/privacy",
  terms: "/terms",
  cookies: "/cookies",
  refund: "/refund",
  accessibility: "/accessibility",
  examDisclaimer: "/exam-disclaimer",
  login: "/login",
  signup: "/signup",
  forgotPassword: "/forgot-password",
  onboarding: "/onboarding",
  plan: "/plan",
  checkoutSuccess: "/checkout/success",
  checkoutCancel: "/checkout/cancel",
  dashboard: "/dashboard",
  exams: "/exams",
  analytics: "/analytics",
  settings: "/settings",
  support: "/support",
  team: "/team",
  exam: (examId: string) => `/exams/${examId}`,
  examSession: (examId: string) => `/exams/${examId}/session`,
  results: (sessionId: string) => `/results/${sessionId}`,
  reviewResults: (sessionId: string) => `/results/${sessionId}/review`,
  admin: "/admin",
  adminUsers: "/admin/users",
  adminQuestions: "/admin/questions",
  adminTickets: "/admin/tickets",
  adminLogs: "/admin/logs",
} as const;

export const READINESS_THRESHOLDS = {
  ready: 80,
  almost: 65,
  inProgress: 50,
} as const;

export const PRICING_TIERS = [
  {
    id: "free",
    productKey: "free" as const,
    name: "Free Trial",
    price: 0,
    priceLabel: "$0",
    priceNote: "one exam",
    pricingType: "free" as const,
    tagline: "Explore before you commit",
    tooltip: "This free experience lets you try the platform and experience a realistic exam simulation before unlocking full readiness analytics.",
    cta: "Start Free",
    highlight: false,
    badge: null,
    features: [
      { text: "1 mock exam included", locked: false },
      { text: "Basic score report", locked: false },
      { text: "Score and pass result", locked: false },
      { text: "Detailed answer review", locked: true },
      { text: "Readiness analytics", locked: true },
      { text: "Pass probability score", locked: true },
      { text: "Weak area analysis", locked: true },
    ],
  },
  {
    id: "single_exam",
    productKey: "single_exam" as const,
    name: "Single Exam Credit",
    price: 39,
    priceLabel: "$39",
    priceNote: "one-time",
    pricingType: "one_time" as const,
    tagline: "One high-quality exam experience",
    tooltip: "Ideal for users who want one premium mock exam with full detailed explanations and realistic exam conditions before investing in complete preparation.",
    cta: "Unlock Premium Exam",
    highlight: false,
    badge: null,
    features: [
      { text: "1 premium mock exam", locked: false },
      { text: "Full detailed explanations", locked: false },
      { text: "Complete answer review", locked: false },
      { text: "Timed simulation mode", locked: false },
      { text: "Per-exam performance breakdown", locked: false },
      { text: "Long-term readiness analytics", locked: true },
    ],
  },
  {
    id: "readiness_pack",
    productKey: "readiness_pack" as const,
    name: "Readiness Pack",
    price: 99,
    priceLabel: "$99",
    priceNote: "one-time",
    pricingType: "one_time" as const,
    tagline: "Everything serious candidates need",
    tooltip: "This complete readiness package gives you realistic practice exams, advanced analytics, readiness intelligence, and detailed performance tracking to maximize pass confidence.",
    cta: "Get Fully Ready",
    highlight: true,
    badge: "Best Value",
    features: [
      { text: "5 full mock exams", locked: false },
      { text: "Permanent readiness analytics", locked: false },
      { text: "Pass probability scoring", locked: false },
      { text: "Weak area analysis", locked: false },
      { text: "Adaptive recommendations", locked: false },
      { text: "Confidence tracking", locked: false },
      { text: "Progress dashboard", locked: false },
      { text: "Unlimited answer review", locked: false },
    ],
  },
  {
    id: "workforce_5",
    productKey: "workforce_5" as const,
    name: "Workforce 5",
    price: 299,
    priceLabel: "$299",
    priceNote: "5 seats",
    pricingType: "one_time" as const,
    tagline: "Self-serve team access",
    tooltip: "Includes five Workforce seats with Readiness Pack access, team seat tracking, and invite management.",
    cta: "Buy Team 5",
    highlight: false,
    badge: null,
    features: [
      { text: "5 team seats", locked: false },
      { text: "Readiness Pack access", locked: false },
      { text: "Team invite management", locked: false },
      { text: "Organization dashboard", locked: false },
    ],
  },
  {
    id: "workforce_10",
    productKey: "workforce_10" as const,
    name: "Workforce 10",
    price: 499,
    priceLabel: "$499",
    priceNote: "10 seats",
    pricingType: "one_time" as const,
    tagline: "More seats, same self-serve flow",
    tooltip: "Includes ten Workforce seats with Readiness Pack access, team seat tracking, and invite management.",
    cta: "Buy Team 10",
    highlight: false,
    badge: "Team Value",
    features: [
      { text: "10 team seats", locked: false },
      { text: "Readiness Pack access", locked: false },
      { text: "Team invite management", locked: false },
      { text: "Organization dashboard", locked: false },
    ],
  },
  {
    id: "workforce_25",
    productKey: "workforce_25" as const,
    name: "Workforce 25",
    price: 999,
    priceLabel: "$999",
    priceNote: "25 seats",
    pricingType: "one_time" as const,
    tagline: "Larger team preparation",
    tooltip: "Includes twenty-five Workforce seats with Readiness Pack access, team seat tracking, and invite management.",
    cta: "Buy Team 25",
    highlight: false,
    badge: null,
    features: [
      { text: "25 team seats", locked: false },
      { text: "Readiness Pack access", locked: false },
      { text: "Team invite management", locked: false },
      { text: "Organization dashboard", locked: false },
    ],
  },
] as const;

export type PricingProductKey = "free" | "single_exam" | "readiness_pack" | "workforce_5" | "workforce_10" | "workforce_25";
