export const APP_NAME = "Readymetry";
export const APP_TAGLINE = "Certification Readiness Engine";
export const APP_URL = process.env.NEXT_PUBLIC_APP_URL ?? "https://readymetry.com";

export const ROUTES = {
  home: "/",
  pricing: "/pricing",
  login: "/login",
  signup: "/signup",
  forgotPassword: "/forgot-password",
  onboarding: "/onboarding",
  plan: "/plan",
  checkoutSuccess: "/checkout/success",
  checkoutCancel: "/checkout/cancel",
  dashboard: "/dashboard",
  exams: "/exams",
  analytics: "/analytics",
  settings: "/settings",
  exam: (examId: string) => `/exams/${examId}`,
  examSession: (examId: string) => `/exams/${examId}/session`,
  results: (sessionId: string) => `/results/${sessionId}`,
  reviewResults: (sessionId: string) => `/results/${sessionId}/review`,
} as const;

export const READINESS_THRESHOLDS = {
  ready: 80,
  almost: 65,
  inProgress: 50,
} as const;

export const PRICING_TIERS = [
  {
    id: "free",
    productKey: "free" as const,
    name: "Free",
    price: 0,
    priceLabel: "$0",
    priceNote: "forever",
    pricingType: "free" as const,
    tagline: "Explore before you commit",
    tooltip: "This free experience lets you try the platform and experience a realistic exam simulation before unlocking full readiness analytics.",
    cta: "Start Free",
    highlight: false,
    badge: null,
    features: [
      { text: "1 mock exam included", locked: false },
      { text: "Basic score report", locked: false },
      { text: "Limited answer review", locked: false },
      { text: "Readiness analytics", locked: true },
      { text: "Pass probability score", locked: true },
      { text: "Weak area analysis", locked: true },
    ],
  },
  {
    id: "single_exam",
    productKey: "single_exam" as const,
    name: "Single Exam",
    price: 39,
    priceLabel: "$39",
    priceNote: "one-time",
    pricingType: "one_time" as const,
    tagline: "One high-quality exam experience",
    tooltip: "Ideal for users who want one premium mock exam with full detailed explanations and realistic exam conditions before investing in complete preparation.",
    cta: "Unlock Premium Exam",
    highlight: false,
    badge: null,
    features: [
      { text: "1 premium mock exam", locked: false },
      { text: "Full detailed explanations", locked: false },
      { text: "Complete answer review", locked: false },
      { text: "Timed simulation mode", locked: false },
      { text: "Readiness score preview", locked: false },
      { text: "Performance breakdown", locked: false },
    ],
  },
  {
    id: "readiness_pack",
    productKey: "readiness_pack" as const,
    name: "Readiness Pack",
    price: 99,
    priceLabel: "$99",
    priceNote: "one-time",
    pricingType: "one_time" as const,
    tagline: "Everything serious candidates need",
    tooltip: "This complete readiness package gives you realistic practice exams, advanced analytics, readiness intelligence, and detailed performance tracking to maximize pass confidence.",
    cta: "Get Fully Ready",
    highlight: true,
    badge: "Best Value",
    features: [
      { text: "5 full mock exams", locked: false },
      { text: "Full readiness analytics", locked: false },
      { text: "Pass probability scoring", locked: false },
      { text: "Weak area analysis", locked: false },
      { text: "Adaptive recommendations", locked: false },
      { text: "Confidence tracking", locked: false },
      { text: "Progress dashboard", locked: false },
      { text: "Unlimited answer review", locked: false },
    ],
  },
  {
    id: "workforce",
    productKey: "workforce" as const,
    name: "Workforce",
    price: null,
    priceLabel: "Custom",
    priceNote: "15 seats minimum",
    pricingType: "contact" as const,
    tagline: "Certification readiness at scale",
    tooltip: "Built for organizations training employees or students at scale. Monitor certification readiness, improve pass rates, and manage compliance across your workforce.",
    cta: "Contact Sales",
    highlight: false,
    badge: null,
    features: [
      { text: "Everything in Readiness Pack", locked: false },
      { text: "Unlimited team members", locked: false },
      { text: "Organization dashboard", locked: false },
      { text: "Employee readiness tracking", locked: false },
      { text: "Certification compliance reports", locked: false },
      { text: "Exportable analytics", locked: false },
      { text: "Admin controls", locked: false },
      { text: "Dedicated support", locked: false },
    ],
  },
] as const;

export type PricingProductKey = "free" | "single_exam" | "readiness_pack" | "workforce";

export const CERT_CATEGORIES = [
  {
    id: "cwi",
    code: "AWS CWI",
    name: "Certified Welding Inspector",
    body: "American Welding Society",
    questionCount: 150,
    examDuration: 180,
    available: true,
  },
  {
    id: "api-570",
    code: "API 570",
    name: "Piping Inspector",
    body: "API",
    questionCount: 70,
    examDuration: 90,
    available: false,
  },
  {
    id: "cweng",
    code: "AWS CWEng",
    name: "Certified Welding Engineer",
    body: "American Welding Society",
    questionCount: 200,
    examDuration: 240,
    available: false,
  },
] as const;
